In [2]:
import numpy as np

In [ ]:
# создание массива из списка
a = np.array([1, 5, 9, 13])
a

array([ 1,  5,  9, 13])

In [ ]:
# создание массива полностью из 0, из 1 и из интервала с шагом
zeros = np.zeros(7)
ones = np.ones(5)
ar = np.arange(0, 15, 3)

zeros, ones, ar

(array([0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([ 0,  3,  6,  9, 12]))

In [ ]:
# создание двумерного массива и вывод его размера и типа данных
matrix_1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix_1.shape, matrix_1.dtype

((3, 2), dtype('int32'))

In [ ]:
# получение конкретного элемента массива
matrix_1[1, 1]

4

In [ ]:
# срез массива
ar[1:4]

array([3, 6, 9])

In [ ]:
# поэлементное сложение и умножение массивов
matrix_2 = np.array([[6, 5], [4, 3], [2, 1]])
matrix_1 + matrix_2, matrix_1 * matrix_2

(array([[7, 7],
        [7, 7],
        [7, 7]]),
 array([[ 6, 10],
        [12, 12],
        [10,  6]]))

In [ ]:
# среднеквадратичное отклонение
np.std(matrix_1)

1.707825127659933